# Generated by Django 6.0.1 on 2026-05-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='steps',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
