# Generated by Django 6.0.1 on 2026-05-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('diyprojects', '0003_alter_projectreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_projects', to='diyprojects.project'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='project_status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('To-Do', 'To-Do'), ('Done', 'Done')], default='To-Do'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reviews', to='diyprojects.project'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
