# Generated by Django 6.0.2 on 2026-05-07 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_project_creator_projectreview_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrating',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diyprojects.project'),
            preserve_default=False,
        ),
    ]
