# Generated by Django 6.0.1 on 2026-02-26 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField()),
                ('publication_year', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('bookcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='bookclub.genre')),
            ],
            options={
                'ordering': ['-publication_year'],
            },
        ),
    ]
