# Generated by Django 6.0.1 on 2026-05-07 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookclub', '0002_alter_bookreview_user_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_bookmarked', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='accounts.profile'),
        ),
    ]
