# Generated by Django 6.0.1 on 2026-05-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('commissions', '0002_alter_commission_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': [models.Case(models.When(status='Open', then=0), models.When(status='Full', then=1), output_field=models.IntegerField()), '-manpower_required', 'role']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.commissiontype'),
        ),
    ]
