# Generated by Django 6.0.1 on 2026-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commission_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': [models.Case(models.When(status='OPEN', then=0), models.When(status='FULL', then=1), output_field=models.IntegerField()), '-manpower_required', 'role']},
        ),
    ]
