# Generated by Django 6.0.1 on 2026-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0002_alter_event_description_alter_eventtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
